#!/usr/bin/env bash
#
# take a quick note to an emacs org-mode file
# example:
# ❯ ./org-note -t "a todo note" "emacs shell"
# * TODO a todo <2016-06-25 Sa>                                      :emacs:shell:

for i in "$@"
do
    case $i in
        -h|--help)
            echo -e "Usage: org-note [-t] HEADLINE [TAGS]

            take a quick note to an emacs org-mode file

            Options:
            -h, --help          show this help message
            -t, --todo          set entry as a TODO"
            exit 0
        ;;
        -t|--todo)
            IS_TODO="TODO "
        ;;
        *)
            # first param != -t = HEADLINE
            # second param != -t = TAGS
            if [ "$HEADLINE" == "" ]; then
                HEADLINE="$i"
            else
                TAGS="$i"
            fi
        ;;
    esac
done

if [ "$HEADLINE" == "" ]; then
    echo "entries need at least a text"
    exit 1
fi

MIN_LINE_LEN=80
NOTE_FILE=$HOME/.notes.org


org_timestamp="<"$(date "+%Y-%m-%d %a")">"
org_headline="* $IS_TODO$org_timestamp $HEADLINE"

if [ "$TAGS" == "" ]; then
    org_tags=""
    spacer=""
else
    # convert given tags to org-mode tags (:tag:)
    org_tags=":"$(echo $TAGS | tr ' ' ':')":"

    # calculate a spacer for tag alignment
    org_line="$org_headline$org_tags"
    org_line_len="${#org_line}"
    delta=1
    if [ $org_line_len -le $MIN_LINE_LEN  ]; then
        delta=$(($MIN_LINE_LEN - $org_line_len))
    fi
    spacer=$(head -c $delta < /dev/zero | tr '\0' ' ')
fi


org_note="$org_headline$spacer$org_tags"
echo "$org_note"
echo "$org_note" >> $HOME/.notes.org
